config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails
  resources :ingredients
  # resources :doses
end


 # do
 #    resources :doses, only: [ :index, :new, :create ]

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]
  def index
    @cocktails = Cocktail.all
  end
  def show
    @doses = @cocktail.doses
  end
  def new
    @cocktail = Cocktail.new
  end
  def create
    @cocktail = Cocktail.new(cocktail_params)

    @cocktail.save
    redirect_to cocktail_path(@cocktail)
  end
  def edit
  end
  def update

    if @cocktail.update(cocktail_params)
      redirect_to @cocktail, notice: 'cocktail was successfully updated.'
    else
      render :edit
    end
  end
  # def destroy
  # @cocktail.destroy
  # respond_to do |format|
  #   format.html { redirect_to _url, notice: 'cocktail was successfully destroyed.' }
  #   format.json { head :no_content }
  # end



 private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end


  def cocktail_params
    params.require(:cocktail).permit(:name, :ingredients, :doses, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredient = Ingredient.new
  end

  def create
    @dose = dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])

    @dose.cocktail = @cocktail

    @dose.save
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<h1>Create a cocktail for <%= @cocktail.name %></h1>

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<head>
  <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
</head>



<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 25%, rgba(0,36,61,0.6) 40%), url('http://dirtymartini.uk.com/wp-content/uploads/2015/12/Cocktails-new-2000x769-1.jpg');">
  <div class="banner-content">
    <h1>JLS's Cocktails </h1>
    <a class="btn-treehouse" href="https:www.youtube.com/watch?v=gIlGnaefCck">Cocktail of the day </a>
    <%= link_to 'New cocktail', new_cocktail_path, class: 'btn-treehouse' %>
  </div>
</div>
<div class="row">

<% @cocktails.each do |cocktail| %>
  <div class="col-sm-12 col-md-4">


  <h4><%= link_to cocktail.name, cocktail_path(cocktail) %></h4>

  <% if cocktail.photo.url %>
  <div class="card"
    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill %>')">
    <div class="card-category">Popular</div>
    <div class="card-description">
      <h2> LA TIZE</h2>
    </div>
    <a class="card-link" href="#" ></a>
  </div>

  <% else %>
  <div class="card"
    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('http://cdn1-www.mandatory.com/assets/uploads/2015/07/man_file_1060278_drunk+guy.jpg');background-repeat: no-repeat;">
    <div class="card-category">Popular</div>
    <div class="card-description">
      <h2>LA</h2>
    </div>
    <a class="card-link" href="#" ></a>
  </div>
  <% end %>

  </div>
<% end %>
</div>

app/views/cocktails/new.html.erb
<h1>New cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<h1>welcome to <%= @cocktail.name %></h1>

<ul>
<% @doses.each do |dose| %>
  <p>Dose: <%= dose.description %></p>
  <p>Ingredient: <%= dose.ingredient.name %></p>
<% end %>
</ul>

<%= link_to 'Edit', edit_cocktail_path(@cocktail) %> |
<%= link_to 'Back', cocktails_path %>

<%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>